spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080

app:
  jwt:
    secret: MyUltraSecretKeyThatIsAtLeast123456789CharsLong1234567890987654321DamnHowMuchCharsDoINeed
    expiration-ms: 86400000